# RocksDB Configuration File
# This file contains tunable parameters for RocksDB performance optimization
# Both gRPC and Thrift servers can use this configuration

[database]
# Database path (will be appended with -rust, -go, -cpp suffixes)
base_path = "./data/rocksdb"

[rocksdb]
# Write buffer size in MB - amount of data to build up in memory before flushing to disk
# Default: 64MB, Recommended: 64-128MB for most workloads
write_buffer_size_mb = 64

# Maximum number of write buffers maintained in memory
# Default: 2, allows for one active buffer and background flushing
max_write_buffer_number = 3

# Block cache size in MB - cache for uncompressed data blocks
# Recommended: ~1/3 of total memory budget (e.g., 512MB for 2GB system)
block_cache_size_mb = 1024

# Block size in KB for SST files
# Default: 4KB, Recommended: 16KB for better compression
block_size_kb = 16

# Maximum number of background jobs (compaction + flush)
# Default: 1, Recommended: 4-8 depending on CPU cores
max_background_jobs = 6

# Bytes per sync - how often to sync WAL writes to disk
# Default: 0 (no syncing), Recommended: 1MB for better crash consistency
bytes_per_sync = 0

# Enable dynamic level sizing for better space utilization
dynamic_level_bytes = true

[bloom_filter]
# Enable bloom filters for point lookups
enabled = true

# Bits per key for bloom filter (higher = lower false positive rate but more memory)
# Default: 10 bits per key (~1% false positive rate)
bits_per_key = 10

[compression]
# Compression type for different levels
# Options: "none", "snappy", "lz4", "zstd", "zlib"
# Recommended: fast compression (lz4/snappy) for upper levels, better compression (zstd) for lower levels

# Compression for L0 and L1 (frequent access, prioritize speed)
l0_compression = "lz4"
l1_compression = "lz4"

# Compression for bottom levels (less frequent access, prioritize space)
bottom_compression = "zstd"

[concurrency]
# Maximum concurrent read operations
max_read_concurrency = 32

[compaction]
# Compaction priority strategy
# Options: "by_compensated_size", "oldest_largest_seq_first", "oldest_smallest_seq_first", "min_overlapping_ratio"
compaction_priority = "min_overlapping_ratio"

# Target file size for L1 in MB
target_file_size_base_mb = 64

# Multiplier for file size at each level
target_file_size_multiplier = 2

# Maximum bytes for L1 in MB
max_bytes_for_level_base_mb = 256

# Multiplier for level size
max_bytes_for_level_multiplier = 10

[cache]
# Cache index and filter blocks in block cache
cache_index_and_filter_blocks = true

# Pin L0 filter and index blocks in cache (reduces cache misses for recent data)
pin_l0_filter_and_index_blocks_in_cache = true

# High priority percentage for index/filter blocks in cache
high_priority_pool_ratio = 0.2

[memory]
# Write buffer manager limit in MB (total memory for all write buffers across column families)
# Set to 0 to disable, recommended to set based on available memory
write_buffer_manager_limit_mb = 256

# Enable write buffer manager to allow sharing memory between column families
enable_write_buffer_manager = true

[logging]
# Log level for RocksDB internal logging
# Options: "debug", "info", "warn", "error", "fatal", "header"
log_level = "info"

# Maximum log file size in MB
max_log_file_size_mb = 10

# Keep maximum number of log files
keep_log_file_num = 5

[performance]
# Statistics level for performance monitoring
# Options: "disable", "except_tickers", "except_histogram_or_timers", "except_timers", "except_detailed_timers", "all"
statistics_level = "except_detailed_timers"

# Enable performance statistics collection
enable_statistics = false

# Dump statistics to LOG periodically (in seconds, 0 to disable)
stats_dump_period_sec = 600