name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-go:
    name: Build Go
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install Protocol Buffers
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install Go protobuf plugins
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Generate protobuf files
      run: ./generate.sh

    - name: Build Go server
      run: |
        cd go
        go mod download
        go build -o ../bin/rocksdbserver main.go

  build-rust:
    name: Build Rust
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Install Protocol Buffers
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Build Rust server
      run: |
        cd rust
        cargo build --bin server

    - name: Build Rust Thrift server
      run: |
        cd rust
        cargo build --bin thrift-server

    - name: Install system dependencies for FFI tests
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential netcat-openbsd

    - name: Run Rust client FFI tests
      run: |
        chmod +x rust/scripts/build_and_run_ffi_tests.sh
        rust/scripts/build_and_run_ffi_tests.sh
