name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-rust:
    name: Build Rust
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        cache: true
        cache-directories: |
          rust/target
          rust/client/target

    - name: Install Protocol Buffers
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Build Rust server
      run: |
        cd rust
        cargo build --bin server

    - name: Build Rust Thrift server
      run: |
        cd rust
        cargo build --bin thrift-server

    - name: Install system dependencies for FFI tests
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential netcat-openbsd librocksdb-dev

    - name: Run Rust client FFI tests
      run: |
        chmod +x rust/scripts/build_and_run_ffi_tests.sh
        rust/scripts/build_and_run_ffi_tests.sh
