name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-go:
    name: Test Go
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install Protocol Buffers
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install Go protobuf plugins
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Install RocksDB
      run: |
        sudo apt-get update
        sudo apt-get install -y librocksdb-dev

    - name: Generate protobuf files
      run: ./generate.sh

    - name: Run Go tests
      run: |
        go mod download
        # Check if there are any Go test files before running tests
        if find . -name "*_test.go" | grep -q .; then
          go test -v ./...
        else
          echo "No Go test files found, skipping tests"
        fi

  test-rust:
    name: Test Rust
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler librocksdb-dev

    - name: Run Rust tests
      run: |
        cd rust
        cargo test --verbose